popup:
  timeout : 1
  probability : 0.2

talkbubble:
  x: 0
  y: 80
  stylesheet: |
      QLabel{background-color: ghostwhite;
          border-style: solid;
          border-width: 5px;
          border-radius: 40px;
          border-color: dodgerblue;
          font: bold 14px;
          min-width: 10em;
          padding: 30px;
          padding-top:30px;
          font-family: Comic Sans MS;
          font-size: 20px;
          color:midnightblue;
      }

animation:
  duration: 500

image: avatar/xmasida.png

override: avatar/clippy.yml