popup:
  timeout : 10000
  probability : 0.2

talkbubble:
  x: 0
  y: 80
  stylesheet: |
      QLabel{background-color: #FFFECB;
          border-style: solid;
          border-width: 1px;
          border-radius: 10px;
          border-color: black;
          font: 10pt;
          min-width: 10em;
          padding: 30px;
          padding-top:30px;
          font-family: "Microsoft Sans", sans-serif;
          font-size: 20px;
          color:midnightblue;
      }

animation:
  duration: 500

image: avatar/xmasida.png